# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_r_base3.4.1target_platformosx-64
    - CONFIG=osx_r_base3.5.1target_platformosx-64

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "U4mkiZf/3Xn4ZKGkJlfhTyZS08IKKZX9LFAzWsrtvnZXPYnrMaCtEyrFgVZF9P6SiX4x8A0hxmewPR0qV5KjGZB05vBq3oASIFUTGTfqTNkBSlCyaG+EyzGmCU7SyPAcykjHQbYpAXn9iYkiU38g+Ve+Hxo5+DEXeIl2IWLJTjnPeq6Aw/NkNm1+pRg/A3MJLn/YellDhqT9pWZE6BF9Z7DYnEzRO+zGS4T4eTt8jI0KPXmfmDdfC1D345Ubo+tx6Yr0zn6SLHQfVpRsE1k+rGRkIsCBTjoSL96pUjTxYBny9yE+GRHe0emJRIpRBJDAko+krvBvjyk1xFad13VV7EPmR5oiF7GknHFzRtWy7nOEu2o+YWirQQHe/wTyZ2gHTMTVYZomo2BVOsE2n7/TEFmDgW7PK0vfHyHED55ZVg8KwhdhS6QwMKBdh2sxRbYdwE0bTlahOh8v3UoQ6re3B9DK7jQUUGPCWERdFdRZ9svyXLgQYwyZmQhsrwQZVwUAdDFBCcdJCt1AshYATlFdiO8vqb1IT04YA0NfUe9JdrzyDTkz2kiop2s8o5dMcrG9ZLrQgcTfekAz567dN+NN5TslHtdnNxRN9GcFdrOuLR9V5zAr8vf0F2tU7gv02JeCiNI01byIGDqTOf4epCS6sVnpdDhfUdrC9UhPjANuHGY="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
